name: announcement_scheduler
description: A Flutter package for scheduling text-to-speech announcements with support for one-time and recurring notifications.
version: 1.0.1
homepage: https://github.com/koorzenb/announcement_scheduler
repository: https://github.com/koorzenb/announcement_scheduler
issue_tracker: https://github.com/koorzenb/announcement_scheduler/issues

environment:
  sdk: ^3.8.1
  flutter: '>=3.35.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_local_notifications: ^19.4.2
  flutter_tts: ^4.0.2
  timezone: ^0.10.1
  hive_flutter: ^1.1.0
  get: ^4.6.6
  permission_handler: ^12.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.4.11
  flutter_lints: ^6.0.0
  flutter_local_notifications_platform_interface: ^9.1.0
  mockito: ^5.4.4
  pub_semver: ^2.2.0

topics:
  - notifications
  - tts
  - scheduling
  - announcements
  - accessibility

platforms:
  android:

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

